volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: cj-theme_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak:
    container_name: cj-theme_keycloak
    image: "quay.io/keycloak/keycloak:24.0.2"
    command: 
      - start-dev
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
      - "--spi-theme-welcome-theme=cj-theme"
      - "--spi-theme-login=cj-theme"
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_HEALTH_ENABLED: true
    volumes:
      - ./themes/cj-theme:/opt/keycloak/themes/cj-theme
      - ./disable-theme-cache.cli:/opt/startup-scripts/disable-theme-cache.cli
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
  psql-client:
    image: rtdl/psql-client:latest
    container_name: psql-client
    volumes:
      - ./scripts/change_realm_theme.sql:/change_realm_theme.sql
    environment:
      PGPASSWORD: keycloak
    entrypoint: psql -h postgres -p 5432 -U keycloak -f /change_realm_theme.sql
    depends_on:
      - postgres
      - keycloak
